SAVE_LOCATION = './WorkingData/Maps/'
DEGREEE_TO_METER = 111139
PROP_PRICE_LOCATION = './Data/PropertyPrices/'
PROP_FILE = PROP_PRICE_LOCATION + 'RSAPropertyPrices.xlsx'
PROVINCE_LOCATION_FILE = './Data/Location/za.json'
POP_FIL = './Data/NASA-SEDAC/gpw-v4-population-density-rev11_2020_2pt5_min_tif/gpw_v4_population_density_rev11_2020_2pt5_min.tif'
YSUM_DIR = './Data/Global Solar Atlas/YearlySum/'
YSUM_GHI = YSUM_DIR + 'GHI.tif'
YSUM_DNI = YSUM_DIR + 'DNI.tif'
YSUM_DIF = YSUM_DIR + 'DIF.tif'
SOLAR_DIR = './Data/Global Solar Atlas/'
SOLAR_FILE = SOLAR_DIR + 'PVOUT_Yearly_sum.tif'
DATA_CENTRE_FILE = './Data/Data centres - preliminary information.xlsx'
SOLAR_EFFICIENCY = 0.2
MAX_POP_SCALE = 1.3
MIN_POP_SCALE = 0.7